/*
 * VTB Group. Do not reproduce without permission in writing.
 * Copyright (c) 2017 VTB Group. All rights reserved.
 */

package ru.vtb.carrent.car.kafka;

import org.mockito.Mockito;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import ru.vtb.carrent.car.domain.entity.Car;
import ru.vtb.carrent.car.message.CarStatusChangedMessage;
import ru.vtb.carrent.car.service.CarService;
import ru.vtb.carrent.car.status.Status;
import ru.vtb.carrent.preorder.dto.MessageContainer;

/**
 * TODO: This is autogenerated Java-Doc
 *
 * @author Nikita_Puzankov
 */
public class CarStatusChangedToMaintenanceConsumerTest {

    CarStatusChangedToMaintenanceConsumer consumer;
    CarService carService;

    @BeforeMethod
    public void setUp() {
        carService = Mockito.mock(CarService.class);
        consumer = new CarStatusChangedToMaintenanceConsumer(carService);
    }

    @Test
    public void testReceive() {
        Long carId = 1l;
        Mockito.when(carService.find(carId)).thenReturn(
                new Car()
        );
        consumer.receive(
                new MessageContainer<>(
                        new CarStatusChangedMessage(
                                carId,
                                Status.IN_STOCK,
                                Status.ON_MAINTENANCE
                        )
                )
        );
    }
}