package ru.vtb.carrent.car.kafka;

import org.mockito.Mockito;
import org.springframework.kafka.core.KafkaTemplate;
import org.testng.annotations.Test;
import ru.vtb.carrent.preorder.dto.MessageContainer;

/**
 * TODO: This is autogenerated Java-Doc
 *
 * @author Nikita_Puzankov
 */
public class SenderTest {

    private Sender sender;

    @Test
    public void testSend() {
        sender = new Sender(Mockito.mock(KafkaTemplate.class));
        sender.send("testTopic", new MessageContainer("testMessage"));
    }
}